### ISSUE TITLE
details of OTU names?

### ISSUE THREAD

**Issue by Ivy-ops** [knights-lab/MLRepo#1]
Hi developer, 

I am interested in the dataset in this repo. However, I can not find the corresponding taxonomy of each OTU. 
For example, the bacteremia dataset has 1852 OTUs in otutable.txt, but with 228 taxonomy taxatable.txt, and there is no key column between the  two tables. 
May I know where can I have these data?

Thanks in advance!
-Ivy

**Comment by mortonjt** [comment]
Since the tables are closed-ref picked from greengenes, I bet that you can extract taxonomies from the greengenes database : https://greengenes.secondgenome.com/?prefix=downloads/greengenes_database/gg_13_5/

**Comment by Ivy-ops** [comment]
Thanks! @mortonjt

**Comment by Gunjan0512** [comment]
Hi developer, 

I am interested in the dataset provided by the ML Repo. However I cannot find out the classification file for OTU Tables. For example, the bacteremia dataset has 1852 OTUs in otutable.txt, but within that file there is no label column i.e particular sample is of bacteremia or non- bacteremia type. 
May I know where can I have that data?

Thanks in advance!
-Gunjan

**Comment by pvangay** [comment]
Hi Gunjan - apologies for the very delayed response. The mapping file is available [here](https://github.com/knights-lab/MLRepo/blob/master/datasets/bacteremia/mapping-orig.txt). The column headers in both the Taxa and OTU files represent the sample names. Hope this helps!
