### ISSUE TITLE
How to use the result of collapase-by-correlation?

### ISSUE THREAD

**Issue by RieSadohara** [knights-lab/MLRepo#4]
Hello, 
I am interested in using the cluster.by.correlation and collapse.by.correlation functions in MLRepo/example/lib/collapse-features.r to decrease the number of features (variables) to be fed into a PCA or cluster analysis.  I was able to run the functions, and it returned the group assignment (variable 1 belongs to group 1, variable 2 belongs to group 2, ... etc.)

How can I use the group assignment in further analysis?  Would it return a new dataset with collapsed variables (i.e. highly correlated variables are thinned into one)?  Or do I pick one variable myself to be fed into downstream analysis, like I pick variable 1 out of variables 1, 5, 9 in group 2, for example?

I hope it makes sense?  Looking forward to hearing from you.   
Rie

**Comment by pvangay** [comment]
Hi Rie, 

You can use the cluster IDs in $reps (which represent OTUs in this example) to filter the OTU table. See for example here:
```
ret <- collapse.by.correlation(otu, .95)
otu <- otu[, ret$reps]
```
https://github.com/knights-lab/MLRepo/blob/master/example/lib/run.cv.datasets.r
